python tools/track_hand_obj_video.py \
  --weight /root/taojianwei/projects/ultralytics/runs/detect/runs/train/exp-21/weights/best.pt \
  --video_dir /root/taojianwei/datasets/IRIS/videos/20260707_videos \
  --output_dir /root/taojianwei/datasets/IRIS/videos/20260707_videos_inference \
  --conf 0.3 \
  --imgsz 640 \
  --virtual_door_enabled \
  --virtual_door_model /root/taojianwei/projects/ultralytics/runs/detect/runs/train/exp-13/weights/best.pt \
  --obj_classification_enabled \
  --hold_confirm_frames 2 \
  --virtual_door_include_anchored_lost \
  --obj_classification_model /root/taojianwei/projects/mobilenetv3.pytorch-master/runs/obj_cls/mobilenetv3_small_224_v2/best.pt
